import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LanguageSelector } from "./_components/language-selector";

const inter = Inter({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Придумать название",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <main className="bg-gray-200 min-h-screen">
          <LanguageSelector />
          {children}
        </main>
      </body>
    </html>
  );
}
